### ISSUE TITLE
Bug in Line no 7

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/QAAZ400#1]
Hi @navodwickra1983 **Please look into
![demo](https://user-images.githubusercontent.com/49720823/169845865-4c2ba9da-483a-4b13-ba6f-1d16ad5e0f51.jpg)
 .** @prcourse230522 Please check and support

**Comment by navodwickra1983** [comment]
Okay, I am working on it.

**Comment by tobyistraining** [comment]
Not got a clue

**Comment by prcourse230522** [comment]
btw city champions

**Comment by bipeensinha** [comment]
Thank You , Let close the Topic
